version: '3.4'
services:
  backend:
  container_name: backend_container_name
  build:
    context: ./backend
  volumes:
    - ./backend:/backend
    - /backend/node_modules
  ports: ['3333:3333']
  env_file:
    - .env
  frontend:
    container_name: frontend_container_name
  build:
    context: ./frontend
    dockerfile: dockerfile
  ports: 
    - '8080:8080'
  env_file:
    - .env